# G:\Project\hongchaoai\frontend\.github\workflows\deploy.yml
name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my_frontend_app:latest .

      - name: Save Docker image
        run: |
          docker save -o my_frontend_app.tar my_frontend_app:latest

      - name: Copy image to server
        uses: appleboy/scp-action@master
        with:
          host: 47.112.109.22
          username: user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "my_frontend_app.tar"
          target: "/var/www/"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 47.112.109.22
          username: user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/
            docker load -i my_frontend_app.tar
            docker-compose -f /var/www/docker-compose.yml up -d